/**
 ******************************************************************************
 * @file    motor_ctrl_step.h
 * @brief   dummy-auk CtrlStep CAN motor protocol driver for RA6M5
 *
 * Protocol summary (compatible with STM32F103 dummy-35motor firmware):
 * - Standard 11-bit CAN frame (non-FD payload, DLC = 8)
 * - CAN ID format: (nodeID << 7) | cmd
 * - Key commands:
 *   0x01: enable / disable motor
 *   0x05: set position (with optional ACK flag in byte4)
 *   0x07: set position + velocity limit
 *   0x0A: set current position as zero (home calibration)
 *   0x0E: clear clog/stall protection latch
 *   0x23: query position (response: float pos + state byte)
 ******************************************************************************
 */

#ifndef MOTOR_CTRL_STEP_H_
#define MOTOR_CTRL_STEP_H_

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ========== Protocol constants ========== */
#define MOTOR_CTRL_STEP_NUM_JOINTS      (6U)
#define MOTOR_CTRL_STEP_CAN_DLC          (8U)

#define MOTOR_CTRL_STEP_CMD_ENABLE       (0x01U)
#define MOTOR_CTRL_STEP_CMD_SET_POS      (0x05U)
#define MOTOR_CTRL_STEP_CMD_SET_POS_VEL  (0x07U)
#define MOTOR_CTRL_STEP_CMD_HOME         (0x0AU)
#define MOTOR_CTRL_STEP_CMD_CLEAR_CLOG   (0x0EU)
#define MOTOR_CTRL_STEP_CMD_CLEAR_STALL  MOTOR_CTRL_STEP_CMD_CLEAR_CLOG  /* backward compatible alias */
#define MOTOR_CTRL_STEP_CMD_QUERY_POS    (0x23U)

/* dummy-auk maintenance commands 0x0A/0x0E use all-zero payload (DLC=8). */

/* Use 0xFF to apply to all joints (implemented as nodeID = 0 broadcast). */
#define MOTOR_CTRL_STEP_ALL_JOINTS       (0xFFU)

/* ========== Joint configuration ========== */
typedef struct
{
    uint8_t node_id;      /* CAN node ID on bus (1..6) */
    bool    inverse;      /* true: logical joint angle is inverted */
    float   reduction;    /* gearbox ratio */
    float   angle_min;    /* software limit (deg) */
    float   angle_max;    /* software limit (deg) */
} motor_ctrl_step_joint_config_t;

/* Public joint configuration table (6 joints, index 0..5). */
extern const motor_ctrl_step_joint_config_t joint_config[MOTOR_CTRL_STEP_NUM_JOINTS];

/* ========== Runtime feedback ========== */
typedef struct
{
    float    target_angle_deg;   /* latest target command in joint angle (deg) */
    float    target_motor_rev;   /* latest target in motor revolution unit */
    float    feedback_angle_deg; /* latest feedback in joint angle (deg) */
    float    feedback_motor_rev; /* latest feedback in motor revolution unit */
    uint8_t  state_byte;         /* raw state byte from node response */
    bool     finished;           /* true when state byte indicates finish */
    bool     online;             /* true after at least one valid response */
    uint32_t last_rx_tick;       /* FreeRTOS tick when last response arrived */
} motor_ctrl_step_feedback_t;

/* ========== Public APIs ========== */

/**
 * @brief Initialize CtrlStep CAN driver.
 * @return 0 on success, negative value on error.
 *
 * Notes:
 * - Uses R_CANFD_Open() with existing g_can0_cfg generated by FSP.
 * - g_can0_cfg nominal timing is already configured as 1 Mbps classic CAN.
 */
int motor_ctrl_step_init(void);

/**
 * @brief Enable/disable one joint or all joints.
 * @param joint_index 0..5, or MOTOR_CTRL_STEP_ALL_JOINTS (0xFF) for broadcast.
 * @param enable true to enable, false to disable.
 * @return 0 on success, negative value on error.
 */
int motor_ctrl_step_set_enable(uint8_t joint_index, bool enable);

/**
 * @brief Send position command (0x05) to one joint.
 * @param joint_index 0..5.
 * @param angle_deg target joint angle in degree.
 * @return 0 on success, -2 when outside joint limits, negative on other errors.
 */
int motor_ctrl_step_set_position(uint8_t joint_index, float angle_deg);

/**
 * @brief Send position + velocity command (0x07) to one joint.
 * @param joint_index 0..5.
 * @param angle_deg target joint angle in degree.
 * @param velocity_deg_s velocity limit in joint degree per second.
 * @return 0 on success, -2 when outside joint limits, negative on other errors.
 */
int motor_ctrl_step_set_position_with_speed(uint8_t joint_index, float angle_deg, float velocity_deg_s);

/**
 * @brief Query current position (0x23) from one joint.
 * @param joint_index 0..5.
 * @return 0 on success, negative on error.
 */
int motor_ctrl_step_query_position(uint8_t joint_index);

/**
 * @brief Set current encoder position as zero (home calibration command).
 * @param joint_index 0..5, or MOTOR_CTRL_STEP_ALL_JOINTS (0xFF) for broadcast.
 * @return 0 on success, negative on error.
 */
int motor_ctrl_step_home(uint8_t joint_index);

/**
 * @brief Clear stall protection latch on one joint or all joints.
 * @param joint_index 0..5, or MOTOR_CTRL_STEP_ALL_JOINTS (0xFF) for broadcast.
 * @return 0 on success, negative on error.
 */
int motor_ctrl_step_clear_clog(uint8_t joint_index);

/**
 * @brief Backward-compatible alias of motor_ctrl_step_clear_clog().
 * @param joint_index 0..5, or MOTOR_CTRL_STEP_ALL_JOINTS (0xFF) for broadcast.
 * @return 0 on success, negative on error.
 */
int motor_ctrl_step_clear_stall(uint8_t joint_index);

/**
 * @brief Poll one RX FIFO (FIFO0) using R_CANFD_Read() and dispatch frames.
 * @return Number of parsed frames (>=0), negative on error.
 */
int motor_ctrl_step_poll_rx(void);

/**
 * @brief Parse one CAN frame for CtrlStep protocol.
 * @param can_id standard 11-bit CAN ID.
 * @param data payload bytes.
 * @param len payload length.
 */
void motor_ctrl_step_rx_callback(uint32_t can_id, const uint8_t * data, uint8_t len);

/**
 * @brief Get latest cached feedback for one joint.
 * @param joint_index 0..5.
 * @param out_feedback output pointer.
 * @return true when parameters are valid and output is written.
 */
bool motor_ctrl_step_get_feedback(uint8_t joint_index, motor_ctrl_step_feedback_t * out_feedback);

/**
 * @brief Notify TX completion from CAN ISR callback.
 *
 * Call this in system CAN callback (CAN_EVENT_TX_COMPLETE) to wake pending TX.
 * This function is optional but improves worst-case TX latency under heavy bus load.
 */
void motor_ctrl_step_tx_complete_notify(void);

/**
 * @brief Check for CAN communication timeout on all joints.
 * @return Bitmask of timed-out joints (bit0-5 for J0-J5), 0 if all OK.
 *
 * A joint is considered timed-out if no response received for 500ms (100 ticks @ 5ms).
 * This function should be called periodically from motion controller.
 */
uint8_t motor_ctrl_step_check_timeout(void);

#ifdef __cplusplus
}
#endif

#endif /* MOTOR_CTRL_STEP_H_ */
